name: Run Project Tests

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'The project number (1, 2, 3a, 3b, or 4) to debug'
        required: true
        default: '1'

  release:
    types: [created, edited]

jobs:
  verify:
    name: 'Verification'
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: 'Setup Java 16'
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'

      - name: 'Test Project'
        uses: usf-cs272-fall2021/action-test-project@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: ${{ github.event.inputs.project }}
